# Generated by Django 5.2.5 on 2026-01-22 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_commentreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreaction',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', '👍'), ('dislike', '👎'), ('love', '❤️')], max_length=10),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
