# Generated by Django 5.2.5 on 2026-01-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_commentreaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', '👍'), ('dislike', '👎'), ('love', '❤️'), ('funny', '😂'), ('angry', '😠'), ('sad', '😢'), ('wow', '😮'), ('confused', '😕'), ('surprised', '😲')], max_length=10),
        ),
    ]
