# Generated by Django 5.2.5 on 2026-01-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_commentreaction_reaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', '👍'), ('dislike', '👎'), ('love', '❤️')], max_length=10),
        ),
    ]
