# Generated by Django 5.2.5 on 2026-01-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
