# Generated by Django 6.0.1 on 2026-01-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
