# Generated by Django 5.2.5 on 2026-01-15 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000, verbose_name='Polling Question')),
                ('description', models.TextField(blank=True, verbose_name='poll Description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_limited', models.DateTimeField(default=0, verbose_name='Time limit')),
                ('is_anonim', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='choice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polling.polling')),
            ],
        ),
    ]
