# Generated by Django 5.2.5 on 2026-01-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.IntegerField(default=1, max_length=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Choice text'),
        ),
        migrations.AlterField(
            model_name='polling',
            name='is_anonim',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='polling',
            name='time_limited',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time limit'),
        ),
    ]
