# Generated by Django 5.2.5 on 2026-01-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_choice_order_alter_choice_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Number of Votes'),
        ),
    ]
