# Generated by Django 5.2.5 on 2026-01-22 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва уроку')),
                ('date_time', models.DateTimeField(verbose_name='Дата і час проведення')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис уроку')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Вчитель')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Оцінка')),
                ('date_recorded', models.DateTimeField(auto_now_add=True, verbose_name='Дата запису оцінки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарі')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учень')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_diary.lesson', verbose_name='Урок')),
            ],
        ),
    ]
